import 'dart:async';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';
import '../models/task_item.dart';
import '../services/api_service.dart';
import '../services/navigation_service.dart';
import '../services/location_correction_service.dart';
import '../services/token_store.dart';
import '../theme/theme_controller.dart';
import '../widgets/task_card.dart';
import '../services/local_contact_controller.dart';
import '../services/local_contact_store.dart';
import '../services/delivery_history_store.dart';
import '../services/phone_action_service.dart';
import '../services/whatsapp_action_service.dart';
import 'login_screen.dart';
import 'scanner_screen.dart';
import 'settings_screen.dart';
